name: Test next release with pytest

on:
  workflow_call:

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "lastest"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests --junitxml=junit/test-results.xml

      - name: Upload pytest results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}
