name: Publish Release

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  version-test:
    name: Test next release with pytest
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/pytest.yml

  release-publish:
    needs: version-test
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "lastest"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build a binary wheel and a source tarball
        run: |
          uv build --sdist --wheel --out-dir dist/ .

      - name: Create a release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
          prerelease: false
          files: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository }}-dist
          path: dist/*x
          retention-days: 7
          if-no-files-found: error

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-publish
    steps:
      - name: Publish the release to PyPI
        uses: ./.github/actions/pypi-publish.yml
        with:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

  done:
    runs-on: ubuntu-latest
    needs: [version-test, release-publish, pypi-publish]
    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Notify
        run: |
          echo "All done!"
          echo "Release published to GitHub and PyPI."
          echo "Check the PyPI page at https://pypi.org/project/${{ github.repository }}"
          echo "Check the GitHub release at httos://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.VERSION }}"
